language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rmedina0531/example-deployment -f Dockerfile.dev .

script:
  - docker run -e CI=true rmedina0531/example-deployment npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: $AWS_ACCESSS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: "us-west-1"
  app: "example-deployment"
  env: "Exampledeployment-env"
  bucket_name: "elasticbeanstalk-us-west-1-691228283948"
  bucket_path: "example-deployment"
  on:
    branch: master
  
