language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rmedina0531/example-deployment -f Dockerfile.dev .

script:
  - docker run -e CI=true rmedina0531/example-deployment npm run test -- --coverage